# Server Configuration
server.port=6767
spring.thymeleaf.encoding=UTF-8
spring.mail.default-encoding=UTF-8

# Debugging
logging.level.org.springframework.web=DEBUG

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=CloudStorageMIPT@yandex.ru
spring.mail.password=dbtvagktncyieszs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000