services:
  ceph:
    image: ceph/daemon:latest
    container_name: ceph-local
    command: demo
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      CEPH_DEMO_UID: ${CEPH_UID}
      CEPH_DEMO_ACCESS_KEY: ${CEPH_ACCESS_KEY}
      CEPH_DEMO_SECRET_KEY: ${CEPH_SECRET_KEY}
      CEPH_DEMO_BUCKET: ${CEPH_BUCKET}
      NETWORK_AUTO_DETECT: "4"
    volumes:
      - ./ceph/etc:/etc/ceph
      - ./ceph/lib:/var/lib/ceph
    restart: unless-stopped
