[global]
fsid = 45ae8eb3-1856-4aef-96dc-206a8edb71d4
mon initial members = fbe7c9f554db
mon host = v2:172.18.0.2:3300/0
osd crush chooseleaf type = 0
osd journal size = 100
public network = 172.18.0.0/16
cluster network = 172.18.0.0/16
osd pool default size = 1
osd max object name len = 256
osd max object namespace len = 64
mon warn on pool no redundancy = false
auth allow insecure global id reclaim = false
osd objectstore = bluestore

[osd.0]
osd data = /var/lib/ceph/osd/ceph-0


[client.rgw.fbe7c9f554db]
rgw dns name = fbe7c9f554db
rgw enable usage log = true
rgw usage log tick interval = 1
rgw usage log flush threshold = 1
rgw usage max shards = 32
rgw usage max user shards = 1
log file = /var/log/ceph/client.rgw.fbe7c9f554db.log
rgw frontends = beast  endpoint=0.0.0.0:8080

