package com.MWS.handlers;

public class UserController {
    public static Object register(spark.Request request, spark.Response response){
        System.out.println("111111111");
    return "<!DOCTYPE html>\n"
        + "<html lang=\"ru\">\n"
        + "<head>\n"
        + "    <meta charset=\"UTF-8\">\n"
        + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        + "    <title>Регистрация - Облачное хранилище</title>\n"
        + "    <style>\n"
        + "        * {\n"
        + "            margin: 0;\n"
        + "            padding: 0;\n"
        + "            box-sizing: border-box;\n"
        + "        }\n"
        + "\n"
        + "        body {\n"
        + "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        + "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
        + "            min-height: 100vh;\n"
        + "            display: flex;\n"
        + "            align-items: center;\n"
        + "            justify-content: center;\n"
        + "        }\n"
        + "\n"
        + "        .container {\n"
        + "            background: white;\n"
        + "            padding: 40px;\n"
        + "            border-radius: 10px;\n"
        + "            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n"
        + "            width: 100%;\n"
        + "            max-width: 400px;\n"
        + "        }\n"
        + "\n"
        + "        .logo {\n"
        + "            text-align: center;\n"
        + "            margin-bottom: 30px;\n"
        + "        }\n"
        + "\n"
        + "        .logo h1 {\n"
        + "            color: #333;\n"
        + "            font-size: 24px;\n"
        + "            font-weight: 600;\n"
        + "        }\n"
        + "\n"
        + "        .form-group {\n"
        + "            margin-bottom: 20px;\n"
        + "        }\n"
        + "\n"
        + "        label {\n"
        + "            display: block;\n"
        + "            margin-bottom: 5px;\n"
        + "            color: #555;\n"
        + "            font-weight: 500;\n"
        + "        }\n"
        + "\n"
        + "        input {\n"
        + "            width: 100%;\n"
        + "            padding: 12px;\n"
        + "            border: 2px solid #e1e5e9;\n"
        + "            border-radius: 6px;\n"
        + "            font-size: 16px;\n"
        + "            transition: border-color 0.3s;\n"
        + "        }\n"
        + "\n"
        + "        input:focus {\n"
        + "            outline: none;\n"
        + "            border-color: #667eea;\n"
        + "        }\n"
        + "\n"
        + "        .btn {\n"
        + "            width: 100%;\n"
        + "            padding: 12px;\n"
        + "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
        + "            color: white;\n"
        + "            border: none;\n"
        + "            border-radius: 6px;\n"
        + "            font-size: 16px;\n"
        + "            font-weight: 600;\n"
        + "            cursor: pointer;\n"
        + "            transition: transform 0.2s;\n"
        + "        }\n"
        + "\n"
        + "        .btn:hover {\n"
        + "            transform: translateY(-2px);\n"
        + "        }\n"
        + "\n"
        + "        .login-link {\n"
        + "            text-align: center;\n"
        + "            margin-top: 20px;\n"
        + "            color: #666;\n"
        + "        }\n"
        + "\n"
        + "        .login-link a {\n"
        + "            color: #667eea;\n"
        + "            text-decoration: none;\n"
        + "        }\n"
        + "\n"
        + "        .error {\n"
        + "            color: #e74c3c;\n"
        + "            font-size: 14px;\n"
        + "            margin-top: 5px;\n"
        + "            display: none;\n"
        + "        }\n"
        + "\n"
        + "        .success {\n"
        + "            color: #27ae60;\n"
        + "            text-align: center;\n"
        + "            margin-top: 15px;\n"
        + "            display: none;\n"
        + "        }\n"
        + "    </style>\n"
        + "</head>\n"
        + "<body>\n"
        + "    <div class=\"container\">\n"
        + "        <div class=\"logo\">\n"
        + "            <h1>\uD83D\uDCC1 Cloud Storage</h1>\n"
        + "            <p>Создайте свой аккаунт</p>\n"
        + "        </div>\n"
        + "\n"
        + "        <form id=\"registerForm\">\n"
        + "            <div class=\"form-group\">\n"
        + "                <label for=\"name\">Имя:</label>\n"
        + "                <input type=\"text\" id=\"name\" name=\"name\" required placeholder=\"Введите ваше имя\">\n"
        + "                <div class=\"error\" id=\"nameError\"></div>\n"
        + "            </div>\n"
        + "\n"
        + "            <div class=\"form-group\">\n"
        + "                <label for=\"email\">Email:</label>\n"
        + "                <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"example@mail.com\">\n"
        + "                <div class=\"error\" id=\"emailError\"></div>\n"
        + "            </div>\n"
        + "\n"
        + "            <div class=\"form-group\">\n"
        + "                <label for=\"phone\">Телефон:</label>\n"
        + "                <input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"+7 (999) 999-99-99\">\n"
        + "                <div class=\"error\" id=\"phoneError\"></div>\n"
        + "            </div>\n"
        + "\n"
        + "            <div class=\"form-group\">\n"
        + "                <label for=\"password\">Пароль:</label>\n"
        + "                <input type=\"password\" id=\"password\" name=\"password\" required placeholder=\"Не менее 6 символов\">\n"
        + "                <div class=\"error\" id=\"passwordError\"></div>\n"
        + "            </div>\n"
        + "\n"
        + "            <button type=\"submit\" class=\"btn\">Зарегистрироваться</button>\n"
        + "            \n"
        + "            <div class=\"success\" id=\"successMessage\">Регистрация успешна!</div>\n"
        + "        </form>\n"
        + "\n"
        + "        <div class=\"login-link\">\n"
        + "            Уже есть аккаунт? <a href=\"#\">Войти</a>\n"
        + "        </div>\n"
        + "    </div>\n"
        + "\n"
        + "    <script>\n"
        + "        document.getElementById('registerForm').addEventListener('submit', function(e) {\n"
        + "            e.preventDefault();\n"
        + "            \n"
        + "            const formData = {\n"
        + "                name: document.getElementById('name').value,\n"
        + "                email: document.getElementById('email').value,\n"
        + "                phoneNumber: document.getElementById('phone').value,\n"
        + "                password: document.getElementById('password').value\n"
        + "            };\n"
        + "\n"
        + "            // Отправка на ваш бэкенд\n"
        + "            fetch('/user/register', {\n"
        + "                method: 'POST',\n"
        + "                headers: {\n"
        + "                    'Content-Type': 'application/json',\n"
        + "                },\n"
        + "                body: JSON.stringify(formData)\n"
        + "            })\n"
        + "            .then(response => response.json())\n"
        + "            .then(data => {\n"
        + "                document.getElementById('successMessage').style.display = 'block';\n"
        + "                console.log('Успешная регистрация:', data);\n"
        + "            })\n"
        + "            .catch(error => {\n"
        + "                console.error('Ошибка:', error);\n"
        + "            });\n"
        + "        });\n"
        + "    </script>\n"
        + "</body>\n"
        + "</html>";
    }
    public static Object login(spark.Request request, spark.Response response){
        System.out.println("111111111");
        return "";
    }
    public static Object UserRegister(spark.Request request, spark.Response response){
        System.out.println(request);
        return "";
    }
}
